#!/usr/bin/env python3
#
#  amalgamate.py
#  TSMoveables
#
#  Copyright 2026 Saxon Herschel Nicholls
#
#  Flattens a TSMoveables header and everything it includes from this library
#  into ONE self-contained file, so the HTTP server can be dropped into a
#  project the way cpp-httplib is: copy one file, include it, link pthreads,
#  done. No include path, no build system, no submodule.
#
#      python3 scripts/amalgamate.py                       # http_server -> single_include/
#      python3 scripts/amalgamate.py ts_moveables.hpp      # the whole library
#      python3 scripts/amalgamate.py event_loop.hpp -o /tmp/loop.hpp
#
#  Local #include "..." lines are replaced by the file's contents, each header
#  expanded exactly once. Everything else - system includes, include guards,
#  the platform #ifs - is copied verbatim, which is what keeps this honest:
#  the amalgamated file is the same code, not a re-rendering of it.
#

import argparse
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "TSMoveables")

LOCAL_INCLUDE = re.compile(r'^\s*#\s*include\s+"([^"]+)"')


def expand(name, seen, out, stack):
    if name in seen:
        return
    if name in stack:
        raise SystemExit("amalgamate: include cycle through " + name)
    path = os.path.join(SRC, name)
    if not os.path.isfile(path):
        raise SystemExit("amalgamate: no such header: " + path)

    seen.add(name)
    stack.append(name)
    out.append("// " + "-" * 70)
    out.append("// begin {}".format(name))
    out.append("// " + "-" * 70)
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            m = LOCAL_INCLUDE.match(line)
            if m:
                out.append("// (inlined) " + line.rstrip("\n"))
                expand(os.path.basename(m.group(1)), seen, out, stack)
            else:
                out.append(line.rstrip("\n"))
    out.append("// end {}".format(name))
    stack.pop()


def main():
    ap = argparse.ArgumentParser(description="Amalgamate TSMoveables headers into one file")
    ap.add_argument("header", nargs="?", default="http_server.hpp",
                    help="entry header in TSMoveables/ (default: http_server.hpp)")
    ap.add_argument("-o", "--output", default=None,
                    help="output path (default: single_include/ts_<name>.hpp)")
    args = ap.parse_args()

    entry = os.path.basename(args.header)
    stem = os.path.splitext(entry)[0]
    name = stem if stem.startswith("ts_") else "ts_" + stem
    output = args.output or os.path.join(ROOT, "single_include", name + ".hpp")

    body = []
    expand(entry, set(), body, [])

    banner = [
        "//",
        "//  {}.hpp - amalgamated single-header build of ts-moveables".format(name),
        "//",
        "//  Copyright 2026 Saxon Herschel Nicholls",
        "//",
        "//  GENERATED by scripts/amalgamate.py from TSMoveables/{} - do not".format(entry),
        "//  edit. Edit the source headers and regenerate.",
        "//",
        "//  Drop this one file into your project, include it, and link pthreads:",
        "//      c++ -std=c++17 -O2 -pthread main.cpp",
        "//",
        "//  https://github.com/saxonnicholls/ts-moveables",
        "//",
        "",
        "#pragma once",
        "",
    ]

    os.makedirs(os.path.dirname(output), exist_ok=True)
    with open(output, "w", encoding="utf-8") as f:
        f.write("\n".join(banner + body) + "\n")

    lines = len(banner) + len(body)
    print("amalgamate: {} -> {} ({} lines, {:.1f} KiB)".format(
        entry, os.path.relpath(output, ROOT), lines, os.path.getsize(output) / 1024.0))


if __name__ == "__main__":
    sys.exit(main())
