#!/usr/bin/env python3
#
#  check_amalgamation.py
#  TSMoveables
#
#  Copyright 2010-2026 Saxon Herschel Nicholls
#
#  The single header must contain the library - every header in the tree,
#  less the ones that are opt-in on purpose because they link a third party.
#
#  `make check-amalgamate` already proves the committed file is not stale and
#  that it compiles. Neither says anything about what is *in* it, and that gap
#  cost a release: http2.hpp was never wired into the umbrella, so the file
#  the README tells people to copy shipped without HTTP/2 while h2spec graded
#  it 147/147 on every push. Staleness could not catch it - the amalgamation
#  faithfully reproduced an umbrella that was itself incomplete.
#
#  So this asks the question directly. Every TSMoveables/**/*.hpp is either
#  in single_include/ts_moveables.hpp or on the OPT_IN list below, and nothing
#  on that list leaks in (it would force -lz or -lssl on everyone). It also
#  fails on:
#
#    - two headers sharing a basename: amalgamate.py expands each basename
#      once, so the second would be silently dropped;
#    - a file in single_include/ that no target regenerates: the drift check
#      only notices files `make amalgamate` rewrites, so an orphan rots in
#      place - which is how ts_server.hpp sat at 1.1 through 1.2.1.
#
#      python3 scripts/check_amalgamation.py
#
#  Exit status 0 when the amalgamation holds the library, 1 when it does not.
#

import os
import sys
from collections import defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "TSMoveables")
SINGLE = os.path.join(ROOT, "single_include")

# Opt-in because each links a library the core does not. Adding to this list
# should be a decision, not a way to make the check pass.
OPT_IN = {
    "tls/openssl.hpp",             # -lssl -lcrypto
    "tls/mbedtls.hpp",             # -lmbedtls
    "http/websocket_deflate.hpp",  # -lz
}

# (output, entry) - must match the `amalgamate` target in the Makefile
GENERATED = {
    "ts_moveables.hpp": "ts_moveables.hpp",
    "ts_http_server.hpp": "http/server.hpp",
}


def begun(path):
    """Basenames amalgamate.py expanded into `path` (its '// begin x' markers)."""
    with open(path, "r", encoding="utf-8") as f:
        return {line[len("// begin "):].strip()
                for line in f if line.startswith("// begin ")}


def main():
    headers = []
    for root, _dirs, files in os.walk(SRC):
        for name in files:
            if name.endswith(".hpp"):
                headers.append(os.path.relpath(os.path.join(root, name), SRC))
    headers.sort()

    problems = []

    by_base = defaultdict(list)
    for h in headers:
        by_base[os.path.basename(h)].append(h)
    for base, paths in sorted(by_base.items()):
        if len(paths) > 1:
            problems.append("basename '{}' is shared by {} - amalgamate.py would keep only one"
                            .format(base, ", ".join(paths)))

    for stale in sorted(OPT_IN - set(headers)):
        problems.append("OPT_IN names '{}', which no longer exists".format(stale))

    umbrella = os.path.join(SINGLE, "ts_moveables.hpp")
    inside = begun(umbrella)
    for h in headers:
        base = os.path.basename(h)
        if h in OPT_IN:
            if base in inside:
                problems.append("opt-in '{}' is inside ts_moveables.hpp - it would force its "
                                "library on every user".format(h))
        elif base not in inside:
            problems.append("'{}' is missing from single_include/ts_moveables.hpp - include it "
                            "from TSMoveables/ts_moveables.hpp, or add it to OPT_IN".format(h))

    for name, entry in sorted(GENERATED.items()):
        path = os.path.join(SINGLE, name)
        if not os.path.isfile(path):
            problems.append("single_include/{} is missing - run 'make amalgamate'".format(name))
        elif os.path.basename(entry) not in begun(path):
            problems.append("single_include/{} does not contain its entry {}".format(name, entry))

    for name in sorted(os.listdir(SINGLE)):
        if name not in GENERATED:
            problems.append("single_include/{} is not generated by 'make amalgamate', so nothing "
                            "keeps it current - delete it or add a target".format(name))

    if problems:
        for p in problems:
            print("check_amalgamation: " + p, file=sys.stderr)
        return 1

    print("check_amalgamation: {} headers - {} in the single header, {} opt-in"
          .format(len(headers), len(headers) - len(OPT_IN), len(OPT_IN)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
